---
- hosts: masters
  gather_facts: true
  remote_user: "{{ user }}"
  tasks:
    - name: Swarm init
      command: "docker swarm init --advertise-addr {{ ansible_hostname }}"

    - name: Get worker token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show worker token
      debug: var=worker_token.stdout

    - name: Master token
      command: docker swarm join-token manager -q
      register: master_token

    - name: Show Master token
      debug: var=master_token.stdout

    - name: Create common network
      command: docker network create common-network -d overlay --subnet 10.0.0.0/16 --attachable



